{% set name = "uritemplate" %}
{% set version = "4.1.1" %}

package:
  name: uritemplate
  version: {{ version }}

source:
  url: https://github.com/python-hyper/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 64cae94edd83bbb0c2c49b15f2cb8192c3f8492af6bc468211d1e8b8496f5791
  skip: True  # [py<39]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - uritemplate
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://uritemplate.readthedocs.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Implementation of RFC 6570 URI Templates
  description: Simple python library to deal with URI Templates.
  dev_url: https://github.com/python-hyper/uritemplate/
  doc_url: https://uritemplate.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
