{%set version = "3.0.0" %}

package:
  name: uritemplate
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uritemplate/uritemplate-{{ version }}.tar.gz
  sha256: c02643cebe23fc8adb5e6becffe201185bf06c40bda5c0b4028a93f1527d011d

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - simplejson >=2.5.0

test:
  imports:
    - uritemplate

about:
  home: http://github.com/uri-templates/uritemplate-py/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'URI Templates'
  dev_url: http://github.com/uri-templates/uritemplate-py/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
