{%set name = "uritemplate" %}
{%set version = "3.0.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "c02643cebe23fc8adb5e6becffe201185bf06c40bda5c0b4028a93f1527d011d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - simplejson >=2.5.0

test:
  imports:
    - uritemplate

about:
  home: http://github.com/uri-templates/uritemplate-py/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'URI Templates'
  dev_url: http://github.com/uri-templates/uritemplate-py/

extra:
  recipe-maintainers:
    - pmlandwehr
