travis:
  secure:
    BINSTAR_TOKEN: eJAZcd8gkBLM5Z18ipzFot/k0fzcGup1rab0Onj5w/g57quYbKYA+8c5gC72d0ugQ2uShPwPVnwQ+jDOkB8M472X/+KSCKuQQgBYDzt/YQpj0WjID0VYlQMIawmM0eZn20OD5soTgXzX++kDtkZobdeK6gsbN2q8Ojuy0qjbI1x012ED23zLVlgJHd2YrITOcrkwFuYsisfeKI/8Tydqy7OrSbE9KTEcI2Fwd0D0o2vbclU/FJDhGyiT+ZkzcNf5d/NUjdX+2FwHu7NAyfauBW59dxSYTgfie7qwhN+iVl0h9SV0cIkOP/wYRpRM8Yc/hNUwxu+oFWfeudnGsoLEHyLeqBZXkAWbDqR2aTZyFQQWLjUKpYRwagoFnotwEQuk7BnEhW7L1SrlrN7atF+QY5w8DBUyVcDfbxVMC7TObCwF6EqikkcRT4IhIAYxfOLjdautvXQ+zLisDQi3wOPBOWIQySps6nTKmvqMkv2vFCeppiDuS12ZVB3ZoAocjjFQYRpE35LHA+YqQ+ILAR+tg1A+WHV3q3bufNWGztFuOsIEIRDCRtmL0lQFBeKUM3SKGGReMXEVryon4DXxjecd2xk0thJ16eGXxSuDNMkrd6aF/AzR7ownrweoNrQfnQ+XuRb+ou2pwiXE0v/CZghH4ywa8dL/XaGO9b50yI5kNZY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
