travis:
  secure:
    BINSTAR_TOKEN: NfMJpJgmjMfvAf2+t4Sfm3F9pCNEFoy8yKvc6mHGF8jwGkV55xnGAlLQjvzb0Xfl9jvS5xgD9sSfXnb711tOyMeY73yTZFqzm/pVtiZxQm2l8HYVxCR8CDla4zNdfhfyLuoZMJAopkreyDmM1OzyFibCjnoNMXuJDw/5JVj0rnY6l2HFn8DngG2NUR0uWlS1CRg/KBXcXqa5T1JufBHoZGEgzMMKV2xgU5VbMa+qZjGykb360lCUMIGXlHXOJgEaHQMf2eYRWlzLwqLJw5kEJVjW5Y0hRklXwhPF4OYaJA9os8r1yGhlmfmV1Lfe9Obu3XF3nH9rbQiW4DznBn3H1JRooHpPVtKHvyvVxegfsYPdYeSwJCjufVuD5rxXNCtqswNOo6qLOaSxxAVTm/J6TcS3h8VuwUnVq9/90IhHTsrtQpJzS9/GEwa+3QPterbLpPhE8GSZKbWQMlsfoPZFoGsxmJ3LtR8GMMQlplfdgZb+uh10JVvDz7zpS2LlW638qW+yG7Q6hYlJOVsLpdIWSKF9LfBDcomDsBXTFrr5kz1Lc3lDmQFXCI+sl/V1E6g4wH7WU4X3iwjkRQ3lqRQR7B6mdd0fu5OUclqnpjorXSL8FLTOHYRA/5S4z80dtAo/XMnt4NFy9vF3VWkGmmY3mIDfoDuS4AkOg0GOfI6IRTE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
