travis:
  secure:
    BINSTAR_TOKEN: wdecrbhVczkCxCnStNelySo1JW3L8Z1X5ZFNgXLEZborpEPaUZ33LBGtc4pXj8Bahem1/NEcpcOS6ktXEGu/2n1nJSNttcggRS0dSQ2lHJeRNSMRBOoFU16oGSbPp71cp8Oajgt97veH6kvTFdxmPDEAVrMDZksfu2/pvPnxkFMfD+IgJxkJ9TlDeKJw95fzOVC1Mr+/7bfFmDWNKwIYjzVxQfjIW4CiIbpJgLl/BOKk21CG3jMn9sLUIdMIYhO7Knbx63iifTQvJcgRVUY5upaq8xdUoV+e+Ile2LaMCV48pLWEYlqNp7hYLEYegMWagdqjR0YGiAGojkTnqeBDyl2pp6UFIV7qUk92uGyROi432Nma4H/pNK5kWk4Z80kSNJaBBhYTcGKlbM3wyegLY515oODJAX55RTOZllG3jW/0yY8ewJnG0wYMKvv6sjeDI3fjz4kPam7YxuxUbQEV1mFnYAodrvi18C53pPtKLaDFV5MlH9/Wu6Fu5zFjIV4g8JAoS5OsssOrWAMg07INS5y77UtnlLtUJJIhBP+XGlVXt1KRQfnKezPjWn4BYMOe3HlN6tWycy4oqM7HRKgiNz0UpY2oFSJC8Hb5jZC0SKQS7pn83cCcBT3ZrP74/2QZxkPlCa9UvRLJTU6y18eKvks4Jlx20wsw3gJp3uz9okI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
